# Generated by Django 4.2 on 2024-05-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='data',
        ),
    ]
